### ISSUE TITLE
lyrics_reader_widget.dart 文件内 handleHighlight 方法数组没有判空

### ISSUE THREAD

**Issue by zhushenwudi** [ozyl/flutter_lyric#10]
<img width="907" alt="WX20220329-164350@2x" src="https://user-images.githubusercontent.com/30340027/160571381-61210047-c965-4f37-972f-1a677aa5f4e5.png">

我目前这样修改来避免页面崩溃

目前正在制作一款开源音乐app，可以加 QQ方便一起修复问题：404288461

**Comment by ozyl** [comment]
👍👍 修复在2.0.2+4
