### ISSUE TITLE
Do we always need to hard code the lyrics in const.dart file?

### ISSUE THREAD

**Issue by deepnrng** [ozyl/flutter_lyric#11]

**Comment by ozyl** [comment]
Did you say example/const.dart ?That's just for example.

**Comment by deepnrng** [comment]
I want to ask how can we show lyrics for random songs?
Currently, there is one lyrics file added in the const.dart and that is hardcoded, how to can we use dynamic lyrics with dynamic songs?

**Comment by ozyl** [comment]
replace YOUR_LYRIC

```
LyricsModelBuilder.create()
      .bindLyricToMain(YOUR_LYRIC)
      .bindLyricToExt(YOUR_LYRIC)
      .getModel();
```

**Comment by deepnrng** [comment]
Do we need to pass the lyrics with time in YOUR_LYRIC?

**Comment by ozyl** [comment]
YOUR_LYRIC is full lyrics, `LyricsModelBuilder` only  just parse.
Look at examples to solve your problem.
