### ISSUE TITLE
[Feature Request] Support User Based Highlighting and Custom Highlight Color

### ISSUE THREAD

**Issue by onurc4kir** [ozyl/flutter_lyric#13]
Example:

[00:12.00]Line 1 lyrics
[00:17.20]F: Line 2 lyrics
[00:21.10]M: Line 3 lyrics
[00:24.00]Line 4 lyrics
[00:28.25]D: Line 5 lyrics
[00:29.02]Line 6 lyrics

Let's say we use blue for male, red for female and pink for Duet. Line 1 using the default color (blue) when no tag is found. Line 2 lyrics start with red when F: is found. Line 3 lyrics start with blue when M: is found. Line 4 lyrics stays blue when no tag is found. Line 5 lyrics start with pink when D: is found. Line 6 lyrics stays pink when no tag is found.

**Comment by ozyl** [comment]
[onurc4kir/flutter_lyric](https://github.com/onurc4kir/flutter_lyric)
