### ISSUE TITLE
example needs update

### ISSUE THREAD

**Issue by shilik** [ozyl/flutter_lyric#16]
Hi,@ozyl 
I have tried your example code. but as the latest version of audioplayers has changed a lot of its apis.
the example codes did not work as expected. Could you please update your example code as well?

**Comment by ozyl** [comment]
Thanks for the feedback, see 48c70691d5a72af945beda4d1d5b1c19d6360966

**Comment by shilik** [comment]
@ozyl  Great. Thanks for the quick response.
