### ISSUE TITLE
About the lyric format

### ISSUE THREAD

**Issue by shilik** [ozyl/flutter_lyric#17]
Hi, @ozyl 
I have two questions regarding lyric format.
I noticed that there is a const  advancedLyric in the lyric.dart. Is there any software can create the content like this?
The second one is I want read a .lrc file from a remote server, as the contents of lyric may change dynamically.
Any suggestion?

**Comment by ozyl** [comment]
1.This field can be omitted if there are no bilingual lyrics. If you simply want a tool, you can see if a well-known local music player offers it.
2.Set a new lyricModel via setState.Try this!
`LyricsModelBuilder.create()
      .bindLyricToMain(normalLyric)
      .bindLyricToExt(transLyric)
      .getModel()`

**Comment by shilik** [comment]
@ozyl  Thanks for the response.
To be clear, I want the effect of advancedLyric that enlarges the fonts size while playing. I am fine with the creation of normalLyric. Just wonder how to get numbers "[11155,1697]I (11155,161)wouldn't (11316,223)mind " before each word.

**Comment by ozyl** [comment]
Dynamic setting new lyricUI object.

Are you asking about the format?
`
"[sentence play time,sentence duration time]I(word play time,word duration time)wouldn't (word play time,word duration time)"`

**Comment by shilik** [comment]
How to set word play time and duration? Is there tool can be used to do the above task?

**Comment by ozyl** [comment]
I've run out of patience to reply to you, so let's end it like this.
