### ISSUE TITLE
lyricStyle TextStyle is not detected

### ISSUE THREAD

**Issue by luisabreu84** [ozyl/flutter_lyric#2]
**Describe the bug**
When a style is applied to lyricStyle the new setting is not being recognized.

**Expected behavior**
Apply the new TextStyle configured in lyricStyle property

Simple Sample: 
`
LyricWidget(
  ...
  lyricStyle: TextStyle(color: Colors.black, fontSize: 24)
)
`

**Smartphone**

Device: iPhone 11, iPHone 6 Plus
OS: iOS 3.6
Flutter Version 1.20.0
flutter_lyric 1.0.2

<img width="331" alt="Screen Shot 2020-08-13 at 11 21 53 PM" src="https://user-images.githubusercontent.com/67016876/90213584-cf042680-ddbb-11ea-8b9a-6add0b818bf7.png">

**Comment by ozyl** [comment]
try use v2.0.0
