### ISSUE TITLE
如何更改歌词颜色

### ISSUE THREAD

**Issue by NiuXiaoGuang** [ozyl/flutter_lyric#21]
我翻阅一段时间API后，没有找到更改歌词颜色的API，可能是我寻找的还不够细致

**Comment by ozyl** [comment]
复制一份ui_netease.dart，修改里面的textStyle

**Comment by NiuXiaoGuang** [comment]
再次感谢，我自定义ui_netease.dart后覆写了getLyricHightlightColor()方法后达到了我想要的结果，再次感谢
