### ISSUE TITLE
歌词闪烁

### ISSUE THREAD

**Issue by zyk-miao** [ozyl/flutter_lyric#22]
您好，我刚学习flutter,我照着示例写了 LyricsReader,autio使用的是just_audio， 我的歌词界面显示有明显的不停的在闪烁，而我看示例的app和web都没有这个问题，希望可以得到您的帮助。
我的LyricsReader 如下
 LyricsReader(
                model: lyricModel,
                playing: true,
                // position: position,
                position: position,
                emptyBuilder: () =>
                    Center(
                      child: Text(
                        "No lyrics",
                        style: lyricUI.getOtherMainTextStyle(),
                      ),
                    ),
              )

**Comment by ozyl** [comment]
检查是否重复生成了lyricModel，只在歌词更改的时候修改lyricModel。。因为新的lyricModel，会刷新LyricsReader。

**Comment by zyk-miao** [comment]
> 检查是否重复生成了lyricModel，只在歌词更改的时候修改lyricModel。。因为新的lyricModel，会刷新LyricsReader。

非常感谢您的回复，我的lyricModel 是声名在state的成员变量 ，初始化是在state的initState函数中

**Comment by zyk-miao** [comment]
您好，请问这个playing初始化必须是false吗，如果初始是true那么就会出现歌词闪烁问题，我这里是绑定的player的播放状态，是每次音乐已经播放了进去歌词界面，此时playing为true,就会出现闪烁问题，如果我固定为false,那么不会有问题且显示功能似乎没有问题，

**Comment by ozyl** [comment]
playing只是控制高亮动画，应该跟它没关系。你可以试下demo

**Comment by git-boya** [comment]
我遇到同样问题了,是因为lyricUi重复创建导致的

**Comment by zyk-miao** [comment]
> 我遇到同样问题了,是因为lyricUi重复创建导致的

我的lyricUi定义是个全局变量
