### ISSUE TITLE
拖动歌词并点击定位后，整个歌词卡住不再滚动

### ISSUE THREAD

**Issue by wellmoonloft** [ozyl/flutter_lyric#23]
作者你好，这里有一个问题，当我把歌词滚动到想要的位置并点击之后

歌词会卡住不再滚动（虽然对应句子的变大效果仍然存在）

必须再次滚动歌词，然后等待定位按钮消失后才会恢复滚动

这个问题在你的两个线上例子里面都可以重现

1. 打开[您的线上demo](https://zylvip.gitee.io/flutter_lyric/#/)
2. 点击播放歌曲
3. 向上拖动歌词，并点击左边的三角，然后整个歌词就会卡住了

**Comment by sine233** [comment]
你是怎么处理的，我现在遇到一样的问题了

**Comment by wellmoonloft** [comment]
太久了 o.o...我真的忘了
我应该是解决了的，你可以看看我仓库里的代码有什么不同

Sine ***@***.***> 于2023年6月15日周四 14:59写道：
