### ISSUE TITLE
歌词逐行

### ISSUE THREAD

**Issue by zyk-miao** [ozyl/flutter_lyric#28]
我的歌词是一行一行的 ,现在逐字显示会感觉对不上节奏，请问怎么可以让歌词显示的时候不是逐字的吗。

**Comment by ozyl** [comment]
ui类中可以配置Highlight，设置false。

**Comment by zyk-miao** [comment]
final lyricUI = UINetease(highlight: false);
设置了false 歌词还是逐字显示的
![图片](https://github.com/ozyl/flutter_lyric/assets/45023244/6bf4cc22-d5ff-4b45-8465-1f5231ef8d8b)
