### ISSUE TITLE
[Feature Request] Allow to align the text

### ISSUE THREAD

**Issue by luisabreu84** [ozyl/flutter_lyric#3]
**Expected behavior**
Allow to align the text to start, center or end

**Sample**:
LyricWidget( 
mainAxisAlignment: MainAxisAlignment.start,
)

**Smartphone**
Device: iPhone 11, iPHone 6 Plus
OS: iOS 3.6
Flutter Version 1.20.0
flutter_lyric 1.0.2

**Comment by hkeyz** [comment]
just go to the lyric_painter.dart file
and make the modification in the code as indicated below:
` lyricTextPaints.addAll(lyrics
        .map(
          (l) => TextPainter(
            **textAlign: TextAlign.center,**
              text: TextSpan(
                  text: l.lyric, style: lyricTextStyle),
              textDirection: TextDirection.ltr),
        )
        .toList());`

**Comment by ozyl** [comment]
support at v2.0.0
