### ISSUE TITLE
deploy your dart song lyrics code in a project of mine

### ISSUE THREAD

**Issue by adoroappnil** [ozyl/flutter_lyric#9]
to implement your dart code for music lyrics in a project of mine, there's a way, when would you charge me to do it
I already have an app ready and it already has a code that shows the lyrics of the song, but I really liked yours and I would like to know if there is a way for you to put it in my project, if you want you can answer my email adoramusicasweb@gmail.com Hug and congratulations for the work.

**Comment by ozyl** [comment]
I can't update the version on pub.dev now, you can try to refer to the git address directly. For example, the following reference method, I have not verified whether it is feasible.
`
dependencies :
   flutter_lyric : 
       git: https://github.com/ozyl/flutter_lyric.git
`

If that doesn't work, you can download the project into your project and use a local reference.
`
dependencies :
   flutter_lyric : 
       path: your local path
`

**Comment by adoroappnil** [comment]
hello, glad you answered, the problem is that I'm not the developer, and my
developer couldn't do it, it's too bad you can't do it for me, now. But if
you do, you can make a price. OK

Em qua., 9 de mar. de 2022 às 22:59, 泡在海里的鱼 ***@***.***>
escreveu:

**Comment by ozyl** [comment]
The communication cost is too high here, you can add my WeChat: wixnxl

**Comment by adoroappnil** [comment]
I'm from Brazil, do you have whatsapp?  if you have add my +5548988717284

Em qua, 9 de mar de 2022 23:52, 泡在海里的鱼 ***@***.***> escreveu:

**Comment by ozyl** [comment]
I'm sorry!I don't have whatsapp.

**Comment by adoroappnil** [comment]
I installed WeChat and it's asking someone to verify it so I can use it,
can you do that for me?  Contact a WeChat user (by call, text or other
method outside of WeChat) who meets the following conditions.
 The.  Sign up for WeChat at least 6 months ago
 B.  Has activated WeChat Pay
 ç.  Did not complete "Verify Friend Registration" for other users in the
past month
 two
 Ask the user to open WeChat, search for "WeChat Team", tap "Account" and
select "Verify Friend Registration".

 3
 Ask the user to enter their mobile number.
 +55 48988717284

Em qui, 10 de mar de 2022 00:33, 泡在海里的鱼 ***@***.***> escreveu:

**Comment by ozyl** [comment]
You try again,That should do it.

**Comment by adoroappnil** [comment]
not sure, you have no other type of contact, Instagram, Facebook, or Skype

Em qui, 10 de mar de 2022 01:44, 泡在海里的鱼 ***@***.***> escreveu:
